### ISSUE TITLE
Video have Their Channel Image

### ISSUE THREAD

**Issue by imhardikdesai** [imhardikdesai/Youtube-Clone#3]
### Description

Set Dynamic Avatar by Video channel

### Scope

- Channel image should be change by video
- ![image](https://github.com/imhardikdesai/Youtube-Clone/assets/87645745/c098059e-1a2d-46b7-bfb9-b1e844fc6576)

### Acceptance Criteria

- You can also Create an Separate issue for any Changes
- All scope are fix correctly, if you have made proper PR and changes then your PR merge by `hacktoberfest` and `hacktoberfest-accepted` label

### Labels

- CSS improvements
- Hacktoberfest
- Responsiveness

**Comment by gandholi-kumar** [comment]
I'm interested to work on this, can you kindly assign this to me?
I have few inputs required from you. 
Can I add the avatar in the "src/db/demodata.js" ?

**Comment by imhardikdesai** [comment]
Hello  @gandholi-kumar ,
I will assign this issue to you if you are interested
- So, avatar is not default value it will comes from API 
- You have to refer `Youtube API` for more information 
- https://developers.google.com/youtube/v3/docs

**Comment by gandholi-kumar** [comment]
Hi @imhardikdesai 

I started working on this bug.
